project_id = "laminar-pipeline"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://127.0.0.1:5173"]
jwt_expiry = 3600
enable_signup = false

[storage]
enabled = true
file_size_limit = "50MiB"
