export const BUSINESS_LAUNCH = {
  id:          'business-launch',
  name:        'Business Launch Playbook',
  shortName:   'Business Launch',
  type:        'deployment',
  version:     '1.0.0',
  description: 'End-to-end playbook for taking a new business from zero to a complete digital presence — domain, website, CRM, Google Business Profile, analytics, and handoff.',

  statuses: [
    { value: 'lead',          label: '⬜ Lead' },
    { value: 'qualified',     label: '🟢 Qualified' },
    { value: 'proposed',      label: '🔷 Proposed' },
    { value: 'active',        label: '🟡 Active' },
    { value: 'blocked',       label: '🔴 Blocked' },
    { value: 'client-review', label: '🔵 Client Review' },
    { value: 'ready-launch',  label: '🟣 Ready for Launch' },
    { value: 'live',          label: '✅ Live' },
    { value: 'completed',     label: '☑️ Completed' },
    { value: 'archived',      label: '🗄️ Archived' },
  ],

  qualification: [
    { id: 'budget-confirmed',    label: 'Budget confirmed' },
    { id: 'timeline-confirmed',  label: 'Timeline confirmed' },
    { id: 'decision-maker',      label: 'Decision maker identified' },
    { id: 'need-understood',     label: 'Business need understood' },
    { id: 'service-fit',         label: 'Service fit confirmed' },
    { id: 'assets-available',    label: 'Client has logo and brand assets available' },
    { id: 'proposal-issued',     label: 'Proposal issued' },
    { id: 'proposal-accepted',   label: 'Proposal accepted' },
    { id: 'scope-approved',      label: 'Scope approved' },
    { id: 'agreement-signed',    label: 'Agreement signed' },
    { id: 'deposit-received',    label: 'Deposit received' },
    { id: 'kickoff-scheduled',   label: 'Kickoff scheduled' },
  ],

  assets: [
    { id: 'logo-primary',    name: 'Primary Logo',           category: 'Brand',    required: true,  description: 'Full colour logo PNG with transparent background' },
    { id: 'logo-icon',       name: 'Logo Icon / Mark',       category: 'Brand',    required: true,  description: 'Square icon version for favicon and social profiles' },
    { id: 'brand-colours',   name: 'Brand Colours',          category: 'Brand',    required: true,  description: 'Hex colour codes for primary and secondary brand colours' },
    { id: 'brand-font',      name: 'Brand Font',             category: 'Brand',    required: false, description: 'Primary brand font name or file' },
    { id: 'photography',     name: 'Business Photography',   category: 'Media',    required: false, description: 'Product, service, team, or location photography' },
    { id: 'biz-description', name: 'Business Description',   category: 'Content',  required: true,  description: 'Short tagline, about paragraph, and services descriptions' },
    { id: 'contact-info',    name: 'Contact Information',    category: 'Content',  required: true,  description: 'Phone, email, address or service area, business hours' },
    { id: 'service-list',    name: 'Services / Products',    category: 'Content',  required: true,  description: 'Services offered with descriptions and pricing guidance' },
    { id: 'domain-info',     name: 'Domain Information',     category: 'Access',   required: true,  description: 'Desired domain name and current registrar if already owned' },
    { id: 'cloudflare-creds',name: 'Cloudflare Credentials', category: 'Access',   required: false, description: 'Stored in Laminar secure credential vault — do not enter here' },
    { id: 'hubspot-creds',   name: 'HubSpot Credentials',   category: 'Access',   required: false, description: 'Stored in Laminar secure credential vault — do not enter here' },
    { id: 'google-creds',    name: 'Google Account Access',  category: 'Access',   required: false, description: 'Business Google account for GBP and Analytics — credentials in vault' },
  ],

  deliverableOptions: [
    'Zoho CRM',
    'Salesforce CRM',
    'Pipedrive CRM',
    'Mailchimp Email Marketing',
    'Constant Contact',
    'Klaviyo Email Marketing',
    'Shopify Store',
    'WooCommerce Integration',
    'Stripe Payment Setup',
    'Square POS Setup',
    'QuickBooks Online Integration',
    'Xero Integration',
    'Wave Accounting Setup',
    'Calendly Booking System',
    'Acuity Scheduling',
    'Zapier Automation',
    'Facebook Pixel Setup',
    'Google Ads Conversion Tracking',
    'Microsoft Clarity (Heatmaps)',
    'Live Chat Integration',
  ],

  deliverables: [
    { id: 'domain',         name: 'Domain Registration & DNS',       description: 'Domain registered and DNS managed through Cloudflare.', clientApprovalRequired: false },
    { id: 'hosting',        name: 'Cloudflare Pages Hosting',        description: 'Website deployed via Cloudflare Pages with automatic deploys from GitHub.', clientApprovalRequired: false },
    { id: 'email-routing',  name: 'Email Routing',                   description: 'Business email address forwarding to client\'s personal inbox via Cloudflare.', clientApprovalRequired: false },
    { id: 'website',        name: 'Website',                         description: 'Responsive, professional website built and live at the client\'s domain.', clientApprovalRequired: true },
    { id: 'hubspot',        name: 'HubSpot CRM',                     description: 'HubSpot account with quote request form, lead capture workflow, and confirmation emails.', clientApprovalRequired: false },
    { id: 'gbp',            name: 'Google Business Profile',         description: 'GBP created, verified, and configured with photos, hours, and service area.', clientApprovalRequired: false },
    { id: 'social-profiles',name: 'Social Media Profiles',           description: 'LinkedIn, Facebook, and Instagram profiles created and branded.', clientApprovalRequired: true },
    { id: 'analytics',      name: 'Google Analytics & Search Console', description: 'GA4 and Search Console configured, sitemap submitted.', clientApprovalRequired: false },
    { id: 'seo-foundation', name: 'SEO Foundation',                  description: 'JSON-LD structured data, Open Graph tags, sitemap, and robots.txt in place.', clientApprovalRequired: false },
    { id: 'documentation',  name: 'System Documentation',            description: 'All account URLs, credentials references, and system documentation delivered to client.', clientApprovalRequired: false },
    { id: 'training',       name: 'Client Training',                 description: 'HubSpot CRM and Google Business Profile training completed and signed off.', clientApprovalRequired: true },
  ],

  training: [
    {
      id: 'hubspot',
      name: 'HubSpot CRM',
      scope: 'Initial orientation — navigating contacts, reviewing form submissions, understanding the lead workflow, and basic CRM management.',
      competencies: [
        'Can log in to HubSpot independently',
        'Can view and navigate the Contacts list',
        'Can open a contact record and review activity',
        'Can understand what happens when a form is submitted',
        'Can locate and review form submissions',
        'Understands how the confirmation and notification emails work',
      ],
    },
    {
      id: 'gbp',
      name: 'Google Business Profile',
      scope: 'Initial orientation — managing business information, responding to reviews, and posting Google Business updates.',
      competencies: [
        'Can log in to Google Business Profile independently',
        'Can update business hours and contact information',
        'Can respond to Google reviews',
        'Can create and publish a Google Business post',
        'Can view basic insights (searches, clicks, calls)',
      ],
    },
    {
      id: 'website-cms',
      name: 'Website & GitHub',
      scope: 'Basic orientation — understanding how the website is hosted, how to make simple text changes, and who to contact for larger updates.',
      competencies: [
        'Understands how the website is hosted (Cloudflare Pages via GitHub)',
        'Knows how to contact Laminar for content updates',
        'Can identify which sections are visible vs. pending (hidden) on the site',
        'Understands what triggers a site re-deploy',
      ],
    },
  ],

  phases: [
    {
      id:'p1', tag:'Phase 1', color:'#1A5FDB',
      title:'Discovery & Kickoff',
      objective:'Gather everything needed to begin implementation immediately — no future back-and-forth delays.',
      tasks:[
        { label:'Discovery call with client', hint:'Services offered, target clients, service areas, competitors, tone/brand preferences' },
        { label:'Collect business details', hint:'Legal business name, phone number, email address, physical address or service area cities' },
        { label:'Collect brand assets', hint:'Logo files (PNG with transparent background preferred), photos, any existing brand colors' },
        { label:'Confirm domain name', hint:'Check availability; register via Cloudflare if not yet owned — avoids transfer complications later' },
        { label:'Set up client project folder', hint:'Create client folder, add contact details and secure credential references' },
        { label:'Create private GitHub repository', hint:'Name: [client-slug]-website, branch: main, initialize with .gitignore' },
      ]
    },
    {
      id:'p2', tag:'Phase 2', color:'#0E8A8A',
      title:'Domain & Hosting Setup',
      objective:'Establish the technical foundation — domain control, deployment pipeline, and email routing — before any build work begins.',
      tasks:[
        { label:'Add domain to Cloudflare', hint:'Transfer registrar or add existing domain; update nameservers at current registrar to Cloudflare' },
        { label:'Create Cloudflare Pages project', hint:'Connect to GitHub repo; no build command; output directory: /' },
        { label:'Verify preview deployment works', hint:'Push to main branch → Cloudflare auto-deploys to [project].pages.dev — confirm it loads' },
        { label:'Set up Cloudflare Email Routing', hint:'Forward info@domain → client\'s personal email; Cloudflare sends a verification email to the destination address' },
        { label:'Client verifies Cloudflare email confirmation', hint:'Client must click the verification link in their personal inbox before routing can be enabled', clientAction:true },
        { label:'Enable routing rule in Cloudflare', hint:'Cloudflare → Email → Email Routing → enable the forwarding rule once client has verified' },
      ]
    },
    {
      id:'p3', tag:'Phase 3', color:'#7C3AED',
      title:'Website Build',
      objective:'Build a professional, production-ready website aligned with the client\'s business strategy and customer journey.',
      tasks:[
        { label:'Set up HTML/CSS foundation', hint:'CSS custom properties for brand colors and fonts; Google Fonts via link tag; CSS reset' },
        { label:'Build core page sections', subs:['Glass nav with logo and anchor links','Hero with headline, subtext, and CTA button','Stats / social proof bar','Service cards (one per service offered)','Why Us / Trust promises section','How It Works / Process steps','About / Founder personal section','Quote request form section','Footer (phone, email, hours, service areas)'] },
        { label:'Add favicon', hint:'<link rel="icon" type="image/png" href="assets/images/logo-icon.png"> — use the icon/mark version of the logo, not the full wordmark' },
        { label:'Add Open Graph meta tags', hint:'og:type, og:url, og:title, og:description, og:image — controls how the link looks when shared on social or iMessage' },
        { label:'Add JSON-LD LocalBusiness structured data', hint:'Helps Google understand the business — name, address, phone, URL, service area, opening hours' },
        { label:'Upload all assets to assets/images/', hint:'Logo variants (transparent PNG), favicon, and any real photos provided by the client' },
        { label:'Mobile responsiveness check', hint:'Test at 375px, 768px, 1200px — nav collapses, cards stack, text is readable, no horizontal scroll' },
        { label:'Check all nav and footer links', hint:'Every anchor link scrolls to the correct section; no dead href="#" placeholders left in' },
        { label:'Remove or hide incomplete sections', hint:'Use style="display:none" on any section with placeholder content — also hide surrounding wave dividers. Record which sections are hidden and what\'s needed to unhide them.' },
        { label:'Push to GitHub', hint:'Commit all files; verify Cloudflare Pages auto-deploys on push to main' },
        { label:'Send preview link to client', hint:'Share the [project].pages.dev URL for review — collect feedback and requested changes' },
        { label:'Apply client revisions' },
        { label:'Client signs off on website content', clientAction:true },
        { label:'Compress and optimise all images', hint:'Use Squoosh (squoosh.app) or TinyPNG. Target under 200 KB for hero images, under 100 KB for secondary images. Convert to WebP where supported. Never upload raw camera files directly.' },
        { label:'Add alt text to all images', hint:'Every <img> tag needs a descriptive alt attribute for accessibility and SEO. Use empty alt="" only for purely decorative images. Describe what the image shows, not "photo of" or "image of".' },
        { label:'Add width, height, and lazy loading to images', hint:'Width and height attributes on every img tag prevent layout shift (improves CLS score). Add loading="lazy" to all below-fold images. Never lazy-load the above-fold hero or logo — it delays LCP.' },
      ]
    },
    {
      id:'p4', tag:'Phase 4', color:'#C2410C',
      title:'HubSpot CRM Setup',
      objective:'Capture every lead automatically and ensure the client can manage relationships from day one without manual tracking.',
      sectionNote:'HubSpot free plan locks form CSS styling behind a paid plan. Default HubSpot styles are acceptable — client can upgrade later if custom form styling is needed.',
      tasks:[
        { label:'Create HubSpot account (free tier)', hint:'Use the client\'s business email — they\'ll own this account long-term' },
        { label:'Create custom "Service Type" contact property', hint:'Settings → Data Management → Properties → Create property. Type: Dropdown. Add one option per service. Must be created here first — it won\'t appear in the form builder otherwise.' },
        { label:'Build the quote request form', hint:'Fields: First Name, Last Name, Email, Phone, Service Type (dropdown), Message. Add reCAPTCHA and privacy consent. Delete the auto-generated form title.' },
        { label:'Publish the form' },
        { label:'Embed form on website using legacy JS method', hint:'Use hbspt.forms.create() — NOT the new hs-form-frame embed. The new embed uses shadow DOM, which blocks all external CSS.' },
        { label:'Set up confirmation email workflow (to lead)', hint:'Workflows → Create → Form submission trigger → Send email. Use "Marketing Email" type — Sales Email is not selectable in workflows on the free plan.' },
        { label:'Set up submission notification to business owner', hint:'Form settings → Notifications → add owner\'s email address' },
        { label:'Test form end-to-end', hint:'Submit a test → verify: contact appears in CRM, confirmation email arrives in lead inbox, notification arrives in owner\'s inbox' },
        { label:'Update HubSpot "From" email to info@domain after go-live', hint:'Requires domain email verification in HubSpot settings — do this after Cloudflare email routing is confirmed live' },
      ]
    },
    {
      id:'p5', tag:'Phase 5', color:'#0F766E',
      title:'Google Business Profile',
      objective:'Establish the client\'s verified presence on Google so they appear in local search and on maps before the site goes live.',
      tasks:[
        { label:'Create or access Google account for business' },
        { label:'Set up Google Business Profile', hint:'business.google.com — add business name, category, phone, email, website URL, service areas, hours' },
        { label:'Upload photos', hint:'Logo, team/founder photo, work samples; before/after photos when available; vehicle or location if applicable' },
        { label:'Complete business verification', hint:'Google typically requires video verification for service-area businesses — client films a walkthrough on their phone. Can take several days to process.', clientAction:true },
        { label:'Copy Google review link', hint:'Once verified: Business Profile → Get more reviews → copy link. Format: https://g.page/r/[ID]/review' },
        { label:'Add review link to website footer' },
        { label:'Unhide Google Reviews sections on site', hint:'Once verified and reviews exist: remove style="display:none" from reviews sections. Restore Reviews nav and footer links.' },
      ]
    },
    {
      id:'p5b', tag:'Phase 6', color:'#BE185D',
      title:'Digital Presence & Social Media',
      objective:'Build a consistent, branded digital presence across all relevant platforms to maximise discoverability and credibility.',
      tasks:[
        { label:'Create LinkedIn Company Page', hint:'Use the client\'s business email; add company name, industry, size, and website URL' },
        { label:'Optimise LinkedIn company profile', hint:'Add logo as profile image, branded cover photo, compelling about section, and specialties' },
        { label:'Create Facebook Business Page', hint:'If applicable to the client\'s audience; use business email; do not use personal account' },
        { label:'Create Instagram Business Account', hint:'If applicable; connect to Facebook Business Page for cross-posting capability' },
        { label:'Configure profile images and cover photos on all platforms', hint:'Use consistent logo and brand imagery across all active profiles' },
        { label:'Add website URL and contact information to all profiles', hint:'Ensure phone, email, website, and service area are consistent across every platform' },
        { label:'Add social profile links to website footer' },
        { label:'Verify consistent branding across all active platforms', hint:'Same logo, colour palette, business name format, and tone across every profile' },
        { label:'Nextdoor Business profile', hint:'Optional but high-value for local service businesses — create at business.nextdoor.com' },
        { label:'Provide client with admin access to all social accounts', hint:'Add client as admin on each platform; confirm they can log in independently', clientAction:true },
      ]
    },
    {
      id:'p6', tag:'Phase 7', color:'#1D4ED8',
      title:'Analytics & Search Indexing',
      objective:'Ensure Google can find and understand the site, and that the client has visibility into traffic and search performance from launch.',
      tasks:[
        { label:'Set up Google Search Console', hint:'Add domain property; verify via Cloudflare DNS TXT record (add in Cloudflare → DNS settings)' },
        { label:'Create and upload sitemap.xml', hint:'Simple XML file listing all page URLs — for a single-page site this is just the homepage with lastmod date' },
        { label:'Submit sitemap in Search Console' },
        { label:'Verify JSON-LD structured data', hint:'Test with Google\'s Rich Results Test tool — confirm no errors on the LocalBusiness schema block' },
        { label:'Set up Google Analytics (optional)', hint:'GA4 tag via gtag.js — confirm with client whether they want traffic tracking before adding' },
        { label:'Run PageSpeed Insights', hint:'Test at pagespeed.web.dev on both mobile and desktop. Target 90+ on Performance. Note LCP (hero image load time), CLS (layout shift — fix with width/height attributes), and FCP. Resolve any critical issues before go-live.' },
      ]
    },
    {
      id:'p7', tag:'Phase 8', color:'#92400E',
      title:'Pre-Launch QA',
      objective:'Systematically verify every deliverable before exposing the site to real customers or sharing it with the client for final sign-off.',
      tasks:[
        { label:'All nav and footer links work' },
        { label:'Form submits and both emails arrive', hint:'Submit a test with a real email — confirm confirmation to lead and notification to owner both land (check spam folders)' },
        { label:'Cloudflare email routing tested', hint:'Send an email to info@domain → confirm it arrives at client\'s personal inbox' },
        { label:'Favicon visible in browser tab' },
        { label:'Open Graph image correct when link is shared', hint:'Paste URL into iMessage or use a link preview checker — confirm correct image, title, and description appear' },
        { label:'Mobile layout clean on phone', hint:'Test on iOS Safari and Android Chrome — check nav, service cards, form, and footer' },
        { label:'No placeholder content visible', hint:'No lorem ipsum, dummy names, fake reviews, or test phone numbers anywhere on the live page' },
        { label:'Client gives final written approval', clientAction:true },
      ]
    },
    {
      id:'p8', tag:'Phase 9', color:'#1A5FDB',
      title:'Go-Live',
      objective:'Activate the live domain, confirm all systems are working under production conditions, and formally complete the delivery.',
      tasks:[
        { label:'Add custom domain in Cloudflare Pages', hint:'Cloudflare Pages → project → Custom Domains → add domain. DNS propagates automatically since domain is already on Cloudflare.' },
        { label:'Confirm SSL certificate is active', hint:'Usually provisions within minutes — confirm https:// loads without browser warnings' },
        { label:'Final check on live domain', hint:'Load the site at the real domain — verify all sections, form, and links on the production URL' },
        { label:'Update HubSpot "From" email to info@domain', hint:'HubSpot → Settings → Domain & URLs → verify domain email; then update the workflow email sender' },
        { label:'Notify client — site is live' },
      ]
    },
    {
      id:'p9', tag:'Phase 10', color:'#166534',
      title:'Post-Launch Handoff',
      objective:'Transfer ownership cleanly, document every system, and establish the foundation for ongoing operational support.',
      tasks:[
        { label:'Document client logins and access', hint:'GitHub repo URL, Cloudflare account, HubSpot portal ID, Google Business account — store securely in Bitwarden, not in this tool' },
        { label:'Deliver client summary handoff note', hint:'What was built, how to access each system, what remains pending (hidden sections, social accounts, etc.)' },
        { label:'Note all hidden sections and what\'s needed', hint:'Before/after photos, Google reviews, social links — record what\'s needed and who\'s responsible for providing it' },
        { label:'Social media handoff confirmation', hint:'Confirm client has admin access to all social accounts created in Phase 6; document profile URLs in client folder' },
        { label:'Enroll client in Operational Support Plan', hint:'Essential Care / Growth Care / Managed Growth — confirm tier and monthly or annual billing', clientAction:true },
        { label:'Schedule first monthly check-in' },
      ]
    },
  ],
};
