export const MOBILE_APP = {
  id: 'mobile-app', name: 'Mobile App Playbook', shortName: 'MAP', type: 'application-delivery', version: '1.0.0',
  description: 'Structured delivery for a mobile product from discovery and validation through build, store release, training, and handoff.',
  qualification: [{ id: 'problem', label: 'User problem and success metric defined' }, { id: 'owner', label: 'Product decision maker identified' }, { id: 'budget', label: 'Budget and delivery approach confirmed' }, { id: 'privacy', label: 'Privacy, data, and compliance needs assessed' }, { id: 'stores', label: 'Release ownership and store accounts confirmed' }],
  assets: [{ id: 'product-brief', name: 'Product Brief', category: 'Product', required: true, description: 'Users, jobs, constraints, success measures, and scope.' }, { id: 'brand-kit', name: 'Brand Kit', category: 'Brand', required: true, description: 'Approved visual identity and product voice.' }, { id: 'store-accounts', name: 'Store Account References', category: 'Access', required: true, description: 'Secure references for Apple and Google release accounts.' }, { id: 'api-access', name: 'API and Service References', category: 'Access', required: false, description: 'Secure references for approved integrations.' }],
  deliverables: [{ id: 'product-spec', name: 'Product Specification', description: 'Approved scope, flows, requirements, and acceptance criteria.', clientApprovalRequired: true }, { id: 'design-system', name: 'Mobile Design System', description: 'Approved visual and interaction system.', clientApprovalRequired: true }, { id: 'release-candidate', name: 'Release Candidate', description: 'Tested mobile build ready for store submission.', clientApprovalRequired: true }, { id: 'store-release', name: 'Store Release', description: 'Published Apple App Store and/or Google Play release.', clientApprovalRequired: true }, { id: 'handoff', name: 'Technical Handoff', description: 'Repository, environments, release process, and support documentation.', clientApprovalRequired: true }],
  training: [{ id: 'product-admin', name: 'Product Administration', scope: 'Operating the delivered product and release/support process.', competencies: ['Can access product administration safely', 'Can identify support and release responsibilities', 'Can request product changes through the agreed process'] }],
  phases: [
    { id: 'map1', tag: 'Discover', title: 'Discovery and Validation', objective: 'Confirm the product problem, users, and delivery case.', color: '#1A5FDB', tasks: [{ label: 'Define user problem and success metrics', clientAction: true }, { label: 'Document user flows and product scope' }, { label: 'Confirm privacy, data, and integration constraints' }] },
    { id: 'map2', tag: 'Design', title: 'Product and Experience Design', objective: 'Create an approved, buildable mobile experience.', color: '#7C3AED', tasks: [{ label: 'Create information architecture and wireframes' }, { label: 'Design key mobile flows and states' }, { label: 'Approve product specification and design', clientAction: true }] },
    { id: 'map3', tag: 'Build', title: 'Application Build', objective: 'Build, integrate, and validate the mobile product.', color: '#0E8A8A', tasks: [{ label: 'Set up repository, environments, and release pipeline' }, { label: 'Implement priority product flows' }, { label: 'Implement approved integrations and analytics' }, { label: 'Complete internal quality assurance' }] },
    { id: 'map4', tag: 'Release', title: 'Acceptance and Release', objective: 'Validate the release candidate and publish safely.', color: '#D97706', tasks: [{ label: 'Coordinate client acceptance testing', clientAction: true }, { label: 'Resolve release-blocking findings' }, { label: 'Prepare store listing, privacy, and release notes' }, { label: 'Submit and publish store release' }] },
    { id: 'map5', tag: 'Handoff', title: 'Training and Handoff', objective: 'Transfer operational knowledge and establish post-launch support.', color: '#16A34A', tasks: [{ label: 'Deliver product administration training', clientAction: true }, { label: 'Deliver technical and release handoff' }, { label: 'Confirm support and change process', clientAction: true }] },
  ],
};
